# Use an official Node.js runtime as the base image
FROM node:14

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json (if available)
COPY package*.json ./

# Install the application dependencies
RUN npm install

# Copy the entire application directory into the container
COPY . .


# Define the command to run your Node.js application
CMD [ "node", "server.js" ]
